infer:
  full_imgsz: 640
  slice_imgsz: 640
  full_conf: 0.01
  output_conf: 0.18
  iou: 0.7
  merge_iou: 0.6
  max_det: 3000
  max_slices: 5
  min_slice_detections: 3
  max_slice_attempts: 12
  device: ""
  feature_layers:
    - 10
  use_cache: true
